### ISSUE TITLE
When message is deleted from notification then message content is deleting and message name stil displaying 

### ISSUE THREAD

**Issue by RaviNelluri** [klinker-apps/messenger-issues#580] opened 2018-01-26 04:49 UTC
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <insert your device: "MacBook Pro on MacOS 10.12, running Chrome v54">
**Primary device:** <insert your phone: "Pixel XL on Android 7.1.2">
**App version:** <insert version: in "My Account" on the phone>
**Steps to reproduce:**

1. step 1
2. step 2
3. step 3

`... more steps`

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine. You can delete this section.

**Comment by klinker24** [comment] 2018-01-26 12:30
Sorry you are going to have to provide me with more information. Please fill in the steps to reproduce, as requested by this template. I do not understand what you are seeing.

When you delete the message from the notification, it is deleted from the conversation.

**Comment by klinker24** [comment] 2018-01-30 12:37
Sorry, without more information, I am not able to reproduce or understand your issue. I am going to have to close this. If you can provide me with the steps to reproduce this, and you follow the template for creating the issue, I can re-open and we can discuss it further.

**Closed by klinker24** 2018-01-30 12:37 UTC
Labels: Not Enough Information, Waiting on Response
