### ISSUE TITLE
On boot, minimize Pulse to tray

### ISSUE THREAD

**Issue by surexor** [klinker-apps/messenger-issues#827] opened 2019-02-02 18:51 UTC
Ability to make Pulse not show when Windows boots. It's incredibly annoying, and not probably not great best practices. Fine if it's minimized, even to tray when I log into Windows. (There's a closed "minimize to tray" issue that doesn't seem to be the same thing.)

- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
A clear and concise description of what you would like to see, and why.

**Describe alternatives you've considered:**
A clear and concise description of any alternative solutions or features you've considered. There may already be something that is built into the app, or the platform, that is very similar.

**Additional information:**

**Comment by klinker24** [comment] 2019-02-02 20:06
I have discussed my thoughts around this in the past. Duplicate of #744.

**Closed by klinker24** 2019-02-02 20:06 UTC
