### ISSUE TITLE
Missing reply bar

### ISSUE THREAD

**Issue by XebraTech** [klinker-apps/messenger-issues#489] opened 2017-10-26 05:08 UTC
**Device with issue**: Mac OSX High Sierra (10.13)
**Primary device**: Same
**App version**: 1.0.0-beta5

**Steps to reproduce**:
1. Open application, select any previous/current conversation
2. There is no way to reply or interact with an existing contact. Entry area at bottom is completely missing.

**Additional information**:
Note that this problem seems to only be on Mac, the Windows version does not exhibit this behavior.

**Comment by klinker24** [comment] 2017-10-26 11:12
A screenshot would be nice. I am not seeing this, nor have I had any reports.

**Comment by klinker24** [comment] 2017-10-29 15:12
Do you have any feedback or updates on this issue? A screenshot would be helpful here. I am not able to reproduce and not sure I understand what you mean. If I don't hear back, I will have to close this.

**Comment by XebraTech** [comment] 2017-10-30 01:01
Hi Luke,

Here’s the screenshot of the missing reply area at bottom of scrollable responses.





Hope that this helps.  Please let me know if there’s anything else you need.  Note that I’m also a developer so can provide logs or anything technical you may need.

Best regards…Bob

**Comment by klinker24** [comment] 2017-10-30 01:06
There is no screenshot attached, sorry

**Comment by XebraTech** [comment] 2017-10-30 05:49
Luke,

Is it possible to send to a private email address?  I’d rather not share my screen shot with the world as it has names/notes that I consider private.  Hope can understand my concern.  If not, then I’m afraid I won’t be able to help you with this issue.

Thx…Bob

**Comment by klinker24** [comment] 2017-10-30 11:09
My email is on the Play Store, or here on GitHub. Anyone can send me emails, yes

**Comment by XebraTech** [comment] 2017-10-31 20:07
Did my private email have the attached graphic and do you need any additional information from me on this issue???

**Comment by klinker24** [comment] 2017-10-31 20:13
I got it and responded to your email. I will investigate this further. I have no clue why it is doing that. I recommend the chrome app, which is not in beta.

https://messenger.klinkerapps.com/overview

**Comment by klinker24** [comment] 2017-11-30 21:07
Can you let me know if this is still an issue with the `beta10` that I released this morning?

**Comment by XebraTech** [comment] 2017-11-30 22:53
Hi Luke,

I saw you had released and pulled down a copy this morning.  The missing reply input area is BACK.  Think you whacked it!  I’ve been running on it all morning/afternoon and haven’t seen ANY problems at all with various chat conversations.  From my perspective, feel free to close the ticket.

As a curiosity, what was the fix?  No worries, if too much to get into.  Just a another developers' curiosity is all.  ;-)

Thanks for the fix, I’m sure enjoying your apps.  I run on 4 platforms.  Mac OSX 11, iOS 11, Android Phone (Nougat), and Windows 10.  Pretty darn nice to be able to keep chats going across all 4 platforms without any problems from my end.  Just depends on where I’m at and what I’m doing at the moment.  It all just WORKS.

Seriously, from another developer….GOOD JOB!

Lates…Bob



Bob McCormick
bobm@xebratech.com<mailto:bobm@xebratech.com>
Cell: (509) 845-7020
Skype: xebratech






On Nov 30, 2017, at 1:07 PM, Luke Klinker <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you let me know if this is still an issue with the beta10 that I released this morning?

**Comment by BlackPR4** [comment] 2017-12-01 01:32
I installed the latest just tonight on Ubuntu 16.04 and am getting the same thing.    Attached screen shot. I had to aggressively censor the content so that nobody would use my Bar Louie coupons.

javac --version
javac 9.0.1

uname -a
Linux ---- 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


![pulse](https://user-images.githubusercontent.com/25537072/33463765-8f5e6af0-d5fc-11e7-9d62-55234f86d85c.jpg)

**Comment by klinker24** [comment] 2017-12-01 12:08
@XebraTech glad it worked for you, I changed the way that the app was packaged, I wasn't sure if it would affect this or not, apparently it did. I am not completely sure why, if I am being honest...

@BlackPR4 is this a new issue for you, or have you always had this problem?

**Comment by BlackPR4** [comment] 2017-12-02 00:40
I installed it for the first time last night.

**Comment by XebraTech** [comment] 2017-12-02 01:20
@BlackPR4 - was a new issue that showed up in that particular version forward until yesterday's version that Luke rolled out yesterday. 

I'll fire up a Linux VM tomorrow to see if it exhibits same issue as you're seeing to see if it's specific to your distro or what. 

What distro/version are you running?

**Comment by BlackPR4** [comment] 2017-12-02 01:33
Ubuntu 16.04 with gnome desktop.

javac --version
javac 9.0.1

uname -a
Linux ---- 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klinker24** [comment] 2017-12-02 01:43
I have the same configuration and I do not see this behavior, unfortunately. I would be interested in confirmation that it is working as expected on the web app @BlackPR4.

**Comment by BlackPR4** [comment] 2017-12-02 02:32
It is working perfectly on the web app.    You using java 9?

**Comment by klinker24** [comment] 2017-12-04 15:11
Are you able to scroll down and see the entire conversion? So I guess I am asking if the window size is just wrong, or if it is literally just the reply bar at the bottom that is missing. Under the `View` item on the menu bar, there are `zoom in` and `zoom out` options

What about inspecting the HTML? You can right click and hit "inspect", like on a web page. There is a `div` with an id of `send-bar` that holds this reply bar. Does it show up, is it invisible, is it off the page, or something else?

Unfortunately I am going to need more information to be able to solve this issue.

**Comment by BlackPR4** [comment] 2017-12-04 15:43
Looks like you're onto something.   It does appear to be the window size.  And now that you mention it, I have had a situation where I receive a reply, I can see it on my phone but can't see it on-screen as it's cut off.   That's a fairly significant symptom, so I'm sorry for not pointing that out sooner!

Here's two screenshots of the bottoms of the pulse windows. .  The first is from the pulse web app.. the second is the desktop app.   

First, the web app:
![image](https://user-images.githubusercontent.com/25537072/33561070-d3811ca8-d8ce-11e7-9844-07da6896dc87.png)



And now, the desktop app:
![image](https://user-images.githubusercontent.com/25537072/33561027-b36b3cbe-d8ce-11e7-9bad-64d190f50808.png)

**Comment by klinker24** [comment] 2017-12-04 16:13
I assume just dragging the corners of the window to change the size doesn't change anything here?

**Comment by BlackPR4** [comment] 2017-12-04 16:35
No, it doesn't... in fact, it changes the cut-off point in unpredictable ways... And if I grab the bottom edge of the window and move it rapidly up and down, I can see the little smiley icon show its face.   But there's something else... when I change the height of the window, the cut-off point at the bottom changes.   So sometimes, after the speech bubble, I can see the date.  If I resize the window, the cut-off point changes and I can't see the date.   I've tried zooming, making the window enormously tall, full-screen, etc...  It is really stubborn about not showing me the bottom.  :)  I tried maximizing it using wmctrl, but the app is absolutely the one calling the shots here (and not the window manager).

**Comment by klinker24** [comment] 2017-12-04 16:53
Interesting, I think this is helpful. I will make some changes around this for the next beta and see what we get.

**Comment by klinker24** [comment] 2017-12-05 13:06
I released `beta13` this morning, if you want to take a look. I do not know if this will change anything or not. There is more I can try, but I wanted to find the simplest solution.

**Comment by BlackPR4** [comment] 2017-12-05 14:15
Nope... That didn't do it.  Just to cover all the bases I went ahead and did a purge of the package and re-installed... no change.  If you have a debug-logging version, I'm happy to help you out.

**Comment by klinker24** [comment] 2017-12-05 15:25
Ok, Pulse is hosted in a `webview` on the window. I really need to know if it is the `webview` element that isn't matching the window size, of if it is the `webview` content that isn't matching the `webview` size. I will walk you through getting me this information using the javascript debugger. You don't need a custom version for this

1. Open the Pulse app
2. Go to `View` -> `Toggle Developer Tools`
3. Hit the `Console` tab at the top
4. Execute the following command and paste the output here: `"window width: " + window.innerWidth + ", window height: " + window.innerHeight`
5. Execute the following command and paste the output here: `"webview width: " + document.getElementById("messenger").offsetWidth + ", webview height: " + document.getElementById("messenger").offsetHeight`
6. Close that debug window
7. Right click on the window content and go to "Inspect"
8. Hit the `Console` tab at the top
9. Execute the following command and paste the output here: `"content width: " + $("body").width() + ", content height: " + $("body").height()`

**Comment by BlackPR4** [comment] 2017-12-05 17:17
No need!   Your instructions prompted me to notice that I had no menubar (and no way to restore it?).   So uhm...    Here was my fix:

sed -i 's/true/false/g' ~/.config/pulse-sms/Settings

Or, for anyone following along, edit the ~./config/pulse-sms/Settings file and change "true" to "false"

**Comment by klinker24** [comment] 2017-12-05 17:21
Tap `alt` to show the menu bar: 

https://messenger.klinkerapps.com/help
https://github.com/klinker-apps/messenger-issues/issues/466

Was that the issue with the reply bar not showing?

**Comment by BlackPR4** [comment] 2017-12-05 19:20
Yes, it was the issue with the bar not showing.  Thanks for your attention on this!

**Comment by klinker24** [comment] 2017-12-05 19:22
Interesting, thanks for the help. I am going to close this then, if others have issues, I will re-direct them here. I know this isn't happening for everyone, so it may be an electron issue.

**Closed by klinker24** 2017-12-05 19:22 UTC
Labels: Bug, Native Desktop
