### ISSUE TITLE
FR: Individual message "locking"

### ISSUE THREAD

**Issue by joshdhart** [klinker-apps/messenger-issues#848] opened 2019-03-17 23:22 UTC
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Samsung Galaxy S10+ 
**Primary device:** Ex: Samsung Galaxy S10+ on Android 9 (Oreo)
**App version:** Ex: v4.7.1.2404

**Describe the FR.**
Ability to "Lock" a single message.
Sometimes I have convo's with people where particular pieces of the discussion are of import. In other texting apps, I have the ability to lock those specific messages. That way when I need to find them later, I can either search through the "locked" messages, or I can delete the convo thread, and ONLY be left with the previously locked  messages. 
IMO this should be a standard feature in a modern texting app, and almost all already have this.

**Comment by klinker24** [comment] 2019-03-18 01:06
Duplicate of #136

**Closed by klinker24** 2019-03-18 01:06 UTC
