### ISSUE TITLE
Wait for signal instead of immediately failing

### ISSUE THREAD

**Issue by ryan77627** [klinker-apps/messenger-issues#868] opened 2019-05-04 03:41 UTC
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
On Android messages, if you have no signal and attempt to send a message, it will simply wait for a connection then proceed to send. On pulse, it will simply fail immediately.

**Describe alternatives you've considered:**
I could switch to Android messages but I don't want to lose scheduled messages and backups and the like.

**Additional information:**
I request this since the signal strength at my house sucks and if I use my phone I usually lose signal entirely but if I put it down at just the right spot I can usually get signal. It's just a little cumbersome to write a message, have it fail to send, wait for signal to return then try sending again.

Thanks for taking time to consider this, love the app! 🤗

**Comment by klinker24** [comment] 2019-05-04 11:31
This is something I will explore for the future. Duplicate of #591

**Closed by klinker24** 2019-05-04 11:31 UTC
