### ISSUE TITLE
Dual Sim Defaults

### ISSUE THREAD

**Issue by sol-systems** [klinker-apps/messenger-issues#715] opened 2018-07-26 00:40 UTC
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <ZTE Blaze v8 Z978, Chrome/Win10, website, chrome ext, app>
**Primary device:** <ZTE Blaze v8 Z978>
**App version:** <3.2.3.2173>
**Steps to reproduce:**

My phone doesn't have a way of making the SMS default to a particular SIM other than the calling default.  The Default Messaging app has 2 sim buttons for sending.

Inside Pulse, when left to the "default" SIM it seems to use the "last" one sent. Likewise on the web and extension, no options are giving to use which number, seems to use the last one used on the phone.  

This will be complicated sending from the right one (work vs. personal) when switching between devices as you'd have actually have sent from the "correct" sim on the phone last to send from the computer from the one you want it from.

Need a way to select and definitively select the sim from all platforms.

**Comment by klinker24** [comment] 2018-07-26 00:42
Duplicate of #649

**Closed by klinker24** 2018-07-26 00:42 UTC
