### ISSUE TITLE
MacOS client keeps crashing/closing

### ISSUE THREAD

**Issue by karma-barma** [klinker-apps/messenger-issues#569] opened 2018-01-18 01:47 UTC
- [ ] I haven't seen anyone else post this yet, so, here goes!

**Device with issue:** <late 2015 iMac, macOS High Sierra 10.13.2">
**Primary device:** <phone: "Pixel 2 on Android 8.1">

**Steps to reproduce:**

1. launch Pulse SMS app
2. wait for random app closure

**Additional information:**

There does not yet seem to be rhyme or reason.  sometimes I will just be viewing conversations and the app closes on its own.  Other times it occurs when I am in the midst of typing a response.

**Comment by klinker24** [comment] 2018-01-18 01:50
Duplicate of #567

**Comment by klinker24** [comment] 2018-01-18 01:51
You should just force quit the app and re-open it. Also discussed on the release page: https://github.com/klinker-apps/messenger-issues/releases/tag/v1.0.1

**Closed by klinker24** 2018-01-18 01:50 UTC
