### ISSUE TITLE
3 groups with the same name in Pulse when I had just one in my devices

### ISSUE THREAD

**Issue by xavierdes** [klinker-apps/messenger-issues#872] opened 2019-05-26 20:35 UTC
Well !!! 
Thanks to the guy who closed some minutes ago my conversation!
Not very fair my friend.
So  I try to explain you again:
I had groups contact in my Apple contacts app, and in my smartphone, they both sync very well since years. 
But… When I use Pulse to write a message to one of these groups,

1) I discover that Pulse shows 2 or 3 groups with the same name where I had just one ! 
Here I send you 2 screenshots of Pulse showing 2 groups called « drome » where it was just ONE in my Apple/Contacts and in my smartphone

2) some of my previous groups don’t appear in Pulse.
 I send you screenshots of - Pulse which doesn’t find my group « perso » - a view of my Apple/Contacts app where you can see the groups « drome » and « perso », as exemple. Best regards
![Capture d’écran 2019-05-26 à 22 21 46](https://user-images.githubusercontent.com/51059502/58386883-6a1dae80-8006-11e9-8dd8-84e7440f3920.png)
![Capture d’écran 2019-05-26 à 22 21 59](https://user-images.githubusercontent.com/51059502/58386884-6a1dae80-8006-11e9-9e4c-d2e478cfea6c.png)
![Capture d’écran 2019-05-26 à 22 23 35](https://user-images.githubusercontent.com/51059502/58386885-6a1dae80-8006-11e9-9ddf-e836dc5a16a1.png)
Xavier
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

**Describe the bug:**

**Steps to reproduce:**

`... more steps`

**Expected behavior:**

**Screenshots:**

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment] 2019-05-26 20:44
This is the correct amount of detail, thank you. You didn't even tell me what platform you were on before. I closed it and told you I would reopen it if you provided the detail that I requested. 

This is a duplicate of issue #840. Thank you for the report. Your issue has now been linked within that one.

**Closed by klinker24** 2019-05-26 20:44 UTC
