### ISSUE TITLE
Web-App Pinned Conservation No Longer Visible

### ISSUE THREAD

**Issue by TerrapinPi** [klinker-apps/messenger-issues#418] opened 2017-08-18 13:22 UTC
**Device with issue:** PC on Windows 10 Professional x64 running Chrome Version 60.0.3112.101 (Official Build) (64-bit)
**Primary device:** SAMSUNG SM-G891A on Android 7.0
**App version:** 2.4.9.1397
**Steps to reproduce:**

1. From the web-app send message to pinned conversation
2. Switch to another conversation
3. At this point (in some instances) the first pinned conversation will no longer be visible

**Additional information:**

I'm unable to reproduce this unfortunately but at times the first pinned conversation in the web-app will disappear when switching to another conversation. The only way I'm able to get that conversation to show up again is by closing the web-app (closing the browser tab) and opening the web-app in a new tab after which the missing pinned conversation is visible again.

**Comment by klinker24** [comment] 2017-08-18 13:34
How often does this happen? I have never heard of, nor seen an issue like this.

**Comment by TerrapinPi** [comment] 2017-08-18 13:47
This only started happening yesterday. I will post back once I can narrow down reproducible steps.

**Comment by TerrapinPi** [comment] 2017-08-18 19:58
Luke, it just happened again... I'm still not sure how to reproduce it but I did get a screen shot.
[PulseMissingPinnedConvo.docx](https://github.com/klinker-apps/messenger-issues/files/1235522/PulseMissingPinnedConvo.docx)

**Comment by klinker24** [comment] 2017-08-18 20:28
I made a change here: https://github.com/klinker41/messenger-web/commit/42bba597da5bd9449e52029519477889afb9138f 
and here: https://github.com/klinker41/messenger-web/commit/748e7907b9483eb5dcce2b1fa86d1947a522babd

I am not going to deploy it yet. I am out of town for the weekend and I have some other web changes in the work I am not comfortable going live. I may do it Sunday or early next week. If you could just watch over next week, that would be great. If you find any reproducible steps, that would be helpful. Right now I am shooting in the dark.

----

**For my own notes:**
*The is the only place that I can see would affect conversation list items not showing. There doesn't seem to be any issues with the resorting logic, so I don't think that that is the problem, but hopefully the cleanup commit makes it clearer what is happening there. The only other real place is on displaying the conversations, but I am not sure why this bit of code would affect this issue. I removed it because it is unnecessary, legacy code.*

*I also looked through the decryption and it will still display the conversation even if the decryption failed, so that isn't where the issue would be. Decryption no longer skips rendering or removes the conversations on the web.*

**Comment by klinker24** [comment] 2017-08-21 17:14
I did go ahead and deploy this change. If you use `ctrl + shift + R`, you can force a reload of the cached javascript and try it out. Please let me know if you think that this has been resolved. I have not been able to replicate it

**Comment by klinker24** [comment] 2017-08-24 02:08
@TerrapinPi have you seen this at all, over the last few days? If not, I am going to go ahead and close it.

**Comment by TerrapinPi** [comment] 2017-08-24 07:51
@klinker24 I did see again, however is on an instance of the browser page that had been open for a few days when the behavior manifested and before a refresh of the page was performed. In the latest instance two of the three pinned conversations were no longer visible. Refreshing the page returned all pinned conversation to a visible state and I have not seen this behavior since. I will let you know should I see this behavior again and I'm able to reproduce somewhat consistently. Thank you for your support on this issue.

**Comment by klinker24** [comment] 2017-08-24 18:58
I am going to go ahead and close this then, yes that old tab would have not had any of the changes. Please feel free to follow up, if you see this start to happen again

**Closed by klinker24** 2017-08-24 18:58 UTC
Labels: Bug, Not Enough Information, Web
