### ISSUE TITLE
Conversation Search

### ISSUE THREAD

**Issue by aswerdlow935** [klinker-apps/messenger-issues#222] opened 2017-01-04 07:25 UTC
Request:
Create some type of search bar for the Chrome app and extension to allow searching of conversations easily without first sending a text
Notes:
As on the phone app, the search button is where the refresh button is on chrome, a search bar could be added in the middle for both the chrome app and extension. It could be a super simple search the already loaded and client-side decrypted. It would be a big UX improvement (more consistency across platforms).

**Comment by klinker24** [comment] 2017-01-04 13:32
Duplicate of: https://github.com/klinker-apps/messenger-issues/issues/182

I am hesitant to add this, since it could really only search conversation titles

**Closed by klinker24** 2017-01-04 13:32 UTC
