### ISSUE TITLE
Intermittent notifications on new text.

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#459] opened 2017-09-18 20:39 UTC
**Device with issue:** Pixel XL
**Primary device:** Pixel XL Oreo 8.0
**App version:** 2.5.6.1546
**Steps to reproduce:**

1. Send text
2. Put phone in sleep mode leaving the conversation open

**Additional information:**

I send a text and put the phone in sleep mode using the power button while leaving the conversation open. When I go to check my phone, there is no notification that I have received a message. When I unlock my phone, It unlocks to the conversation list and shows the new text message(s) in bold. I am trying to recreate the problem but it seems to be intermittent. I have only noticed it since the latest update.

**Comment by klinker24** [comment] 2017-09-18 20:58
Fairly confident that this is a duplicate of #455. Seems like there is something off with the management of which conservations are active. This issues has now been linked to that one

**Closed by klinker24** 2017-09-18 20:58 UTC

**Comment by Skullmonkey** [comment] 2017-09-18 22:26
I don't believe these are related. It sounds like his notifications are while the screen is on. Mine is a lack of notifications when the screen is off. This includes all notifications and not just the active conversation.

**Comment by klinker24** [comment] 2017-09-18 22:34
They are the same thing. 

The bug is the management of the active conversation and when the notification should be displayed. When that issue is fixed, this will be too.
