### ISSUE TITLE
Auto Reply Mode

### ISSUE THREAD

**Issue by aminsol** [klinker-apps/messenger-issues#595] opened 2018-02-20 20:33 UTC
When I'm in a meeting I mute my phone and I like to send a custom text to whomever that texts me during that time. There are some apps already doing this but they aren't texting apps. Other texting apps don't have this.

Also, I know this is not possible on iPhone because their SDK does not provide any API to send text. If you can add this to android version, it would be great.

Thank you,
Amin

**Comment by klinker24** [comment] 2018-02-20 20:35
Duplicate of #359.

**Closed by klinker24** 2018-02-20 20:35 UTC
