### ISSUE TITLE
WearOS Slow Notifications

### ISSUE THREAD

**Issue by JetRocket11** [klinker-apps/messenger-issues#860] opened 2019-04-14 06:20 UTC
Issue: Notifications on WearOS are slow to appear or do not show up at all.

*I have read the existing FAQ but don't feel that using WiFi is a fix or work around for WearOS devices

It is hard to always have a WearOS device connected to WiFi. If you are saying that Bluetooth connection is unreliable for notifications to work then perhaps this feature should be redesigned. As mentioned in another closed post for same issue, Google Messages notifications come through immediately even without WiFi and allow you to reply.

If I delete your app from my watch then notifications are instant but then you can't reply/compose.

Question is if this works fine with Google Messages without WiFi, why doesn't the same work with your app?

I only need to receive a notification instantly and be able to dismiss it or reply.

**Comment by klinker24** [comment] 2019-04-14 12:14
Pulse does not work the same way as Android Messages and is architected completely differently. This is explained in the FAQ and is directly stated in the closed referenced topic. At this time, there are no changes or gains that can be made around this, sorry. 

There are benefits and drawbacks to both apps architecture. By doing it my way, I enable the app to be used on a much wider range of devices, not just through the web and an Wear OS app. At this time, my architecture will not be changing, and neither will my answer to this issue.

Duplicate of #850

**Closed by klinker24** 2019-04-14 12:14 UTC
