### ISSUE TITLE
TIZEN 4.0.0.2  not receiving alerts for incoming texts to Samsung Gear Classic S3

### ISSUE THREAD

**Issue by spencerinaustin** [klinker-apps/messenger-issues#823] opened 2019-01-28 06:56 UTC
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

**Describe the bug:**

**Steps to reproduce:**

`... more steps`

**Expected behavior:**

**Screenshots:**

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by spencerinaustin** [comment] 2019-01-28 07:09
Device with issue: Samsung S3 Classic Gear Watch
Primary device: Moto G 5th Gen
App version: Ex: v4.5.0.2340

Describe the bug:
I receive alerts on the watch for other apps.  When new messages arrive to Pulse, there is no notification on the watch.

Steps to reproduce:

Messages come in and its quiet on the watch.

Your site has this listed:
"Notifications for Pulse will continue to be mirrored from the app on your Android phone, like any other app. To enable notifications for Pulse, you can open the Galaxy Watch app on the phone and configure the notifications from settings."
I have followed these steps.  Notifications are in fact turned on.
I have tried installing and uninstalling the apps on the phone and watch.
I am about to send and receive messages on the watch EXCEPT there is not alert or notification.

I am on Android 8.0.0

**Comment by klinker24** [comment] 2019-01-28 12:50
Duplicate of https://github.com/klinker-apps/messenger-issues/issues/797

Pulse does not control the notifications for your watch. You need to set up mirroring for the app, though the Galaxy Gear app on your phone. Pulse does not control this process at all.

**Closed by klinker24** 2019-01-28 12:50 UTC

**Comment by spencerinaustin** [comment] 2019-01-30 23:02
Many thanks.  It was a setting on the watch after all.  You can close this case

On another note,

I have noticed it’s difficult to compose messages on the watch with the tiny screen.   Have you tried this yourself?

**Comment by Gr3m1yn** [comment] 2019-02-19 14:34
Spencer, do you remember what setting it was. My notifications are mirrored but issue persists.

**Comment by spencerinaustin** [comment] 2019-02-19 16:51
It turned out to be that my watch was set for Alerts Only.  Once I turned up the volume one increment, I started getting notifications.  Hope that helps.

**Comment by spencerinaustin** [comment] 2019-02-19 16:56
It turned out to be that my watch was set for Alerts Only.  Once I turned up the volume one increment, I started getting notifications of all types.  Hope that helps.

**Comment by Gr3m1yn** [comment] 2019-02-19 17:23
Thanks that solved it!

**Comment by absolutesyn2** [comment] 2019-04-17 17:47
I have tried all the suggested actions and it still does not work for me...
