### ISSUE TITLE
Need larger view when writing an email on web and extentions.

### ISSUE THREAD

**Issue by Shadowonx** [klinker-apps/messenger-issues#185] opened 2016-12-09 17:15 UTC
As of now it just shows one line at a time. That makes it hard to keep track on what I write.

**Comment by klinker24** [comment] 2016-12-09 17:26
Duplicate of this one: https://github.com/klinker-apps/messenger-issues/issues/163

For now, the two lines are all I will be able to provide.

**Closed by klinker24** 2016-12-09 17:26 UTC
