### ISSUE TITLE
System messaging app shows "Sending...", Pulse doesn't

### ISSUE THREAD

**Issue by junkbondtrader** [klinker-apps/messenger-issues#664] opened 2018-05-06 08:59 UTC
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Affects message state on web app and Android app
**Primary device:** Honor 5X on Android 6.0.1
**App version:** 2.11.1.2072
**Steps to reproduce:**

1. Lose signal
2. Send a text message
3. Fail to send
4. Continue sending texts

*Expected:*
Pulse shows "Sending..." state when the system messaging app shows "Sending..."

*Actual:*
Pulse displays no state (i.e. "Sent") when the system messaging app shows "Sending..."

**Additional information:**

The system messaging app has shown this behavior several times:
When a message fails to send due to lack of signal, all subsequent texts get stuck behind it. After deleting all stuck texts, I'm able to send texts again.

The behavior described above is obviously not caused by Pulse, but in the system messaging app, all stuck messages show "Sending..." whereas in Pulse, nearly all display no state (i.e. "Sent").

Unfortunately for the purposes of bug investigation, I resolved the stuck "Sending..." issue on my device so I can't say for certain what the initial failed message's state was in Pulse. The system messaging app showed a big red exclamation point on the conversation to let me know that a message had failed. I think I would've noticed if Pulse had showed me the same. I'm quite confident I did not receive a "failed" notification from Pulse. I can open a separate issue for this, if appropriate.

I should be able to repro, if requested.

This was problematic for me as I use Pulse as my default SMS client, so I didn't notice that my texts hadn't been sending for exactly 7 days.

**Comment by klinker24** [comment] 2018-05-06 11:06
I'm not really sure what to say about this, or what I will be able to do. When Pulse is the default messaging app, I am in charge of updating that "sending..." status in the shared database as well as my own database. Android provides a simple callback for updating that state. The stock messaging app should follow exactly what Pulse has, because it doesn't have any other way to get that status information unless they have some kind of direct integration with your carrier that provides it.

When Pulse sends a message, it sits and waits for Android to report a "sent" or "failed" status. When Android makes this report, Pulse writes those statuses to it's own database, as well as the shared database.

https://github.com/klinker41/android-smsmms/blob/master/library/src/main/java/com/klinker/android/send_message/SentReceiver.java

I don't have any extra information on top of what your phone provides to me. I can't see that "sending..." message being the cause of backed up traffic for a whole week either. Android doesn't sequentially send messages like that and any of them would have sent on their own, rather than being queued up behind the other one. Messages are sent asynchronously and will always fail after some time. If it was truly stuck with Android trying to send it, it would have torn through your battery as well.

**Comment by junkbondtrader** [comment] 2018-05-06 17:44
> I'm not really sure what to say about this, or what I will be able to do.

> I don't have any extra information on top of what your phone provides to me.

I figured this might be the case.

While this sucks, it doesn't suck so much that I'd give up Pulse. Especially now that I know this is the case and I can compensate for it by checking the system messaging app.

> When Pulse is the default messaging app, I am in charge of updating that "sending..." status in the shared database as well as my own database. Android provides a simple callback for updating that state.

Would I perhaps be better off using the Pulse app, but leaving the system app as the default?

> I can't see that "sending..." message being the cause of backed up traffic for a whole week either.

I assure you that I've seen this behavior on at least 3 separate occasions and the story is always the same. I wouldn't dare venture an explanation.

> If it was truly stuck with Android trying to send it, it would have torn through your battery as well.

Huawei's additions to Android do seem invasive to me. Certainly possible this is their messaging app or they're mucking with things. I wouldn't be know the difference.

Thanks for the response, the source link, and the details on how messaging works on Android. Very interesting.

**Comment by klinker24** [comment] 2018-05-06 17:59
Pulse has to be the default app, or else it isn't going to work correctly, sorry. I'm not sure what I am going to be able to do about this one, unfortunately, or that I have enough info to do anything at all right now. I am going to close it as a question and an issue with Android, rather than Pulse. If you get any more information or see anything else about this, in the future, feel free to comment back here and we can discuss it further

**Closed by klinker24** 2018-05-06 17:59 UTC
Labels: Not Enough Information, Question
