### ISSUE TITLE
Pulse not showing in top tray area in Ubuntu 17.10

### ISSUE THREAD

**Issue by M-W99** [klinker-apps/messenger-issues#578] opened 2018-01-25 04:02 UTC
**Device with issue:** <"HP 15 Laptop running Ubuntu 17.10">
**Primary device:** <"Samsung Galaxy S8 running Android 7.0">
**App version:** <"Linux Client v1.0.1">
**Steps to reproduce:**

1. Open Pulse SMS on Ubuntu 17.10
2. Observe that it does not show up in the top tray area

My apologies for submitting yet another issue, but hopefully this time it's actually something reproducible and not just isolated to my device.
Recently I made the switch to Ubuntu 17.10 which uses the GNOME desktop environment. Pulse doesn't show up in the top tray area like it did in Unity. GNOME uses a different system for tray icons I believe, but Ubuntu has an extension (Ubuntu appindicators) installed to make it behave like Unity did. I tested another program that's made to sit in the tray (redshift-gtk) and it works as expected, so I'm assuming that it's an issue with Pulse.

If there's any more information I can provide that would help, please let me know.
Thanks!

**Comment by klinker24** [comment] 2018-01-25 13:14
It seems as though this is an upstream issue and not something that I will be able to solve within my app: https://github.com/electron/electron/issues/10887

I am going to close this as a duplicate of that upstream issue.

**Closed by klinker24** 2018-01-25 13:14 UTC
Labels: Bug, Native Desktop

**Comment by M-W99** [comment] 2018-02-13 20:14
Here's a workaround for anyone who is experiencing the same issue: http://www.dangtrinh.com/2017/04/fix-slacks-icon-tray-missing-in-ubuntu.html

https://github.com/electron/electron/issues/9046#issuecomment-315804938
