### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#210] opened 2016-12-31 19:31 UTC
I've notified when you have say, a unread message from a previous thread, you get duplicate notifications alert when you get a new message from a different contact.  Example: you get messages from 4 people today. Let's say you're ignoring one or two of those persons. But you check everyone elses messages. When one of those other persons send a new message.  Notifications comes up again for everything that's unread.  So you're alerted for those two unread messages, again and as well as the new message. 

This is very noticeable on my Fitbit Charge HR 2 and only happens with Pulse.   I also seen it from the Pulse app itself. 

Issue is annoying as it alerts me too many times through the day than just one time. This causes extra battery drian on my Fitbit. 

Android 7.1.1. 

Latest verison of Pulse.  1.13.2.834 

Last app reset: Last week.

**Comment by klinker24** [comment] 2016-12-31 19:38
Can you tell me a bit more, or post screenshots of the duplicates you are seeing? When you swipe away the notification, it gets marked as seen and will not give another notification until a new message comes into that conversation. I can confirm that this is the behavior I am seeing as that it seems to be working correctly, however, I may not understand your use case

**Comment by pbanj** [comment] 2017-01-06 01:30
i dont think this is a pulse issue tbh. i have seen this with a few other apps. i think its an issue with android itself as it seems to do it randomly. sometimes it will dupe them, other times it wont. for what its worth i havent had pulse do it yet.

**Comment by klinker24** [comment] 2017-01-06 01:36
Could be. I have made some changes tonight regardless, I am going to close this one, feel free to reopen with more info, if it keeps happening after the next update

**Closed by klinker24** 2017-01-06 01:36 UTC
Labels: Android, Not Enough Information

**Comment by ram130** [comment] 2017-01-12 19:33
So I got to test this on other apps. I only seen the same issue on an app called Mysms.  Apps like Google Messenger, Hangouts and others don't have this duplicate notification issue. What info do you need? It seems Pulse sending the alert of all unread messages when a new unread message comes in.

**Comment by ram130** [comment] 2017-01-14 13:59
Hello. Should I reopen on this as a new issue? I also pulse doing the duplicate notifications on my phone too.
