### ISSUE TITLE
Not able to view sent contact cards

### ISSUE THREAD

**Issue by mick077** [klinker-apps/messenger-issues#200] opened 2016-12-24 07:41 UTC
I was sent a contact card but had to use a different app to view it. Not sure if it is an issue or a feature that needs to be added?

**Comment by mick077** [comment] 2016-12-24 07:42
The issue was occurred on a 5 inch pixel running Android 7.1.1

**Comment by klinker24** [comment] 2016-12-24 13:41
Duplicate of: https://github.com/klinker-apps/messenger-issues/issues/191

I have made changes for the next version.

**Closed by klinker24** 2016-12-24 13:41 UTC
