### ISSUE TITLE
Windows 10 App renders dictionary of information

### ISSUE THREAD

**Issue by small-pants** [klinker-apps/messenger-issues#836] opened 2019-02-15 22:47 UTC
**Device with issue:** Dell XPS 13 9360, Windows 10 Build 1809
**Primary device:** Pixel 2 on Android Pie
**App version:** v3.2.1

**Describe the bug:**
Opening Pulse natively (including on startup) results in the window displaying what looks like a dictionary of internal information being rendered. Opening the Pop-up Window using the taskbar icon context menu produces normal results and the app works fine. 

**Steps to reproduce:**

1. Launch Pulse on startup or manually using the native Windows app.

**Expected behavior:**
Conversations to render.

**Screenshots:**
![capture](https://user-images.githubusercontent.com/7059931/52888455-b5900900-3149-11e9-8496-6fd4ffb97e53.PNG)

**Additional information:**
I'm going to check this on my Ubuntu system as well and update this issue with results. I've already tried reinstalling etc.

**Comment by klinker24** [comment] 2019-02-15 23:57
I really have no idea why that is, and I am not able to reproduce it with the step you provided (or I wouldn't have released it, obviously..)

The Windows app is open source, you can check it out and see for yourself what could be causing that

https://github.com/klinker-apps

**Comment by klinker24** [comment] 2019-03-10 13:49
Sorry but without more information or steps to reproduce this, I am going to have to close it. Since you didn't follow up about Ubuntu, I do assume that it works correctly there. It seems like this must have something to do with your system configuration, since I have not received any other reports of issues around this

**Closed by klinker24** 2019-03-10 13:49 UTC
Labels: Bug, Native Desktop, Not Enough Information
