### ISSUE TITLE
Support for Windows 10 onscreen keyboard in Tablet Mode

### ISSUE THREAD

**Issue by vincethewipet** [klinker-apps/messenger-issues#469] opened 2017-09-21 16:38 UTC
The Pulse native app doesn't show the onscreen keyboard on Windows 10 when touching a text input field with a touchscreen in Tablet Mode. It would be nice if the app showed the onscreen keyboard in that situation, like others UWP and Win32 apps.

Tried with a fully updated Surface Pro 3, with the latest beta of the Pulse Messanger native app.

Thank you for the app :)

**Comment by klinker24** [comment] 2017-09-21 16:45
It looks like this is the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=497381
There is also a Electron issue open to address this: https://github.com/electron/electron/issues/6430

Until the upstream issues are fixed, this isn't something that I will be able to tackle in Pulse, so I am going to close the request here, as a duplicate of those upstream issues. 

I will definitely watch those issues and update this when it becomes available, but a fix will unfortunately not come on my end.

**Closed by klinker24** 2017-09-21 16:45 UTC
