### ISSUE TITLE
Galaxy Watch Active 2 login fields not accessible

### ISSUE THREAD

**Issue by Xophys** [klinker-apps/messenger-issues#945] opened 2019-12-26 03:11 UTC
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have one watch, therefore I cannot verify that this is something that is reproducible.

**Device with issue:** Samsung Galaxy Watch Active 2 44mm
**Primary device:** LGG6 H873 on Android 9
**App version:** v1.0.5 [TizenOS]

**Describe the bug:**
Upon opening the app on the Galaxy Watch Active 2, I am prompted with a keyboard to enter my username, as expected, but as soon as that keyboard dissapears by any method (i.e. hitting go or hitting back button) I cannot click on the Username or Password fields to bring it back up....they cannot be accessed.

This means it is only possible to enter my username/email when the app first launches, but impossible no matter what to enter my password because once the keyboard dissapears, it seems to be gone for good

Here's a video of the issue for you, I know my descriptions can be sometimes vague
https://www.dropbox.com/s/3dqsxvulwph4ea7/20191225_213213.mp4?dl=0

**Comment by klinker24** [comment] 2019-12-26 03:19
Duplicate of #943. 

Samsung said that they were releasing a fix for it. It should be rolling out to all devices over the next few days.

This issue does not have anything to do with Pulse, nor can I provide any workarounds on my end.

**Closed by klinker24** 2019-12-26 03:19 UTC
