### ISSUE TITLE
Notification opening second instance of application

### ISSUE THREAD

**Issue by timmytot666** [klinker-apps/messenger-issues#473] opened 2017-09-27 19:07 UTC
**Device with issue:** Ubuntu Linux Desktop Client
**App version:** Desktop Beta 2
**Steps to reproduce:**

1. Have Pulse native running,
2. Get a message pop up in the notification center,
3. Click Message
4. Another instance of Pulse SMS opens up instead of opening the current process.

**Comment by klinker24** [comment] 2017-10-01 20:19
Does this happen every single time for you? I am not able to reproduce it

**Comment by timmytot666** [comment] 2017-10-01 20:26
Yes.

**Comment by klinker24** [comment] 2017-10-01 20:39
What version of Ubuntu are you on?

**Comment by timmytot666** [comment] 2017-10-01 20:43
16.0.4.3 let's xenial

**Comment by captnpineapple** [comment] 2017-10-04 22:35
I also get this on Windows 10 client, same steps as above.

**Comment by klinker24** [comment] 2017-10-05 12:44
Fixed with: https://github.com/klinker41/messenger-chrome/commit/0b543bbba8dbdc5d9e3dbfd0d106410bdc642610

It will be released with `v1.0.0-beta3`.

**Closed by klinker24** 2017-10-05 12:44 UTC
Labels: Bug, Native Desktop
