### ISSUE TITLE
Full message history is not and cannot be loaded

### ISSUE THREAD

**Issue by ArcticZeroo** [klinker-apps/messenger-issues#702] opened 2018-07-01 15:36 UTC
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Pixel 2 XL on P Beta (don't think this matters though)
**Primary device:** ^
**App version:** 3.2.0.2160
**Steps to reproduce:**

1. Have a lot of SMS messages in one thread.
2. Switch to pulse
3. Most of those messages are no longer available in that thread. They are still stored in the system though.

**Additional information:**

I have about 28,000 messages in a thread with one person. On Android Messages, all these messages displayed fine. When I scrolled up using the scroll bar... thing, on the right, it would properly scroll to the start of our thread a year or so ago. I also use the app SMS Backup which tells me how many messages it just backed up for me. After switching to Pulse, apparently I have about 5,000 TOTAL sms messages across all conversations, which can't possibly be right. SMS Backup reports that it backed up 34,000 messages last night, so something is off.

I understand that all nearly 30,000 messages shouldn't be loaded into memory due to performance concerns but it shouldn't give me an incorrect count either, and if I want it would be nice to allow it to load those old messages.

**Comment by klinker24** [comment] 2018-07-01 15:42
Sorry, Pulse loads the latest 500 messages in any conversation. At this time, this limit is not planned to increase.

Duplicate of #292, #450.

**Comment by ArcticZeroo** [comment] 2018-07-01 15:43
👍  is there any chance of getting an FAQ entry on it? I tried doing searching to figure out what was going on, but nothing came up in my googling

**Closed by klinker24** 2018-07-01 15:42 UTC

**Comment by klinker24** [comment] 2018-07-01 15:47
Search "limit" or "import":

https://messenger.klinkerapps.com/help

The topic is "why don't all my messages get imported when I load the app for the first time"

**Comment by ArcticZeroo** [comment] 2018-07-01 15:47
Aha, guess I'm just bad at searching. Thanks!

**Comment by pizdek** [comment] 2018-07-29 22:14
It's possible to Increase this limit please ?
With a pop-up when the are more messages, and you can choose or not to restore the totality.
Thank you for your work.

**Comment by Skullmonkey** [comment] 2018-07-31 13:25
> Pulse will import a max of 250 conversations and 500 messages per conversation on the initial import. Sorry, this is a hard limit, and will not be something that I will change at this

>I made the limit on purpose, it isn't something I plan to add a workaround for, sorry.

Taken from #450
