### ISSUE TITLE
Unable to insert text in Chrome extension

### ISSUE THREAD

**Issue by gadgetrex** [klinker-apps/messenger-issues#283] opened 2017-03-10 20:24 UTC
### Cannot insert text (type) in Pulse Chrome extension

**Device with issue:** Mac Pro running OSX 10.11.6 and Chrome v56.0.2924.87 (64-bit)
**Primary device:** LG V20 running Android 7.0
**App version:** 2.1.0.1039
**Steps to reproduce:**

1. Select/press Chrome extension icon
2. Pulse window opens
3. Attempt to respond/reply to a message
4. Unable to input text, as if the keyboard is not working

**Additional information:**

Able input text on Pulse website, https://messenger.klinkerapps.com/conversations.html#, accessed through the same version of Chrome
No problem responding from my phone, either

**Comment by klinker24** [comment] 2017-03-10 20:59
I have no idea why this is. The extension is just a web wrapper, so I don't actually have control over the widgets.

**Comment by gadgetrex** [comment] 2017-03-10 22:06
Strange to me, too. I don't have a problem with any other extensions that I can think of. Similarly, I had no problem when I was using Mightytext.

**Comment by klinker24** [comment] 2017-03-10 22:12
If you figure anything out, please let me know

**Comment by gadgetrex** [comment] 2017-03-10 22:14
My guess is that one of the other Chrome extensions is interfering, somehow. When I have some time, I will selectively disable them, in an effort to discover which one it is.

**Comment by gadgetrex** [comment] 2017-03-10 22:16
FYI,  Adblock, Adblock Plus, Ghostery, Collusion, Google Analytics Opt-Out and Twitter Disconnect seem the most likely suspects.

**Comment by jeremytiki** [comment] 2017-03-13 01:19
I am having a similar issue, however I found that if I use a popout window (top right corner, second button from the right) the issue does not persist to the new popout window.

**Comment by klinker24** [comment] 2017-03-13 02:24
Yeah that popup window isn't the extension anymore, it is just a chrome window

**Comment by klinker24** [comment] 2017-03-17 13:31
I had one user report that hitting the "Tab" button will get you to be able to write into the extension. Is this something that others are seeing?

**Comment by klinker24** [comment] 2017-03-17 14:57
I did make a few very small changes to the text input, today. If someone could follow up on whether or not it is different, that would be good. I am not really expecting a change here, the change I made was for something a bit different, but it could have affected this as well.

**Comment by gadgetrex** [comment] 2017-03-17 17:32
Hitting the "Tab" button worked for me, too.

**Comment by rnhurt** [comment] 2017-03-30 12:28
I'm experiencing the same issues on my system; the Chrome extension doesn't seem to accept text input but the pop-out window works fine.

* Chrome Version 58.0.3029.33 beta (64-bit)
* macOS 10.12.4

So far I really love the Android app and am hoping that Pulse can replace Hangouts for me on both the desktop and mobile platforms.

**Comment by jwkicklighter** [comment] 2017-03-30 22:15
I've also noticed an issue pasting into web wrappers on MacOS, maybe it's related to that.

e.g. chrome extensions, Boxy.app (Gmail wrapper)

**Comment by marcusmotill** [comment] 2017-04-10 15:34
In response to @rnhurt I was experiencing this issue then tried the 'tab' solution, now I cannot reproduce the bug but the app works as expected.  Which is awesome for me as a user but infuriating for the dev team 😢

**Comment by ginnsquad** [comment] 2017-06-08 14:45
I also had the same problem but I tried the "tab method" that @rnhurt suggested and it worked. Really odd.
* Chrome Version 58.0.3029.110 (64-bit)
* MacOS 10.11.6

**Comment by thatchrismiller** [comment] 2017-06-08 16:40
I thought I would add a bit of info to this. I am also a Mac user and frequently use Opera alongside Chrome. Opera has the option to run Chrome extensions. (It is build on Chromium with a different UI wrapper.) I installed Pulse. For a while, it worked correctly (allowed me type without tabbing) while the Chrome version did not. However, after a recent Opera update, it started to have the same issues as Chrome. Opera is usually a version or two behind in which version of Chromium it is based on. This makes me think that something changed in the underlying code of Chrome/Chromium that cause this. It just hit Chrome sooner because they are using the most recent build. 

Just my two cents.

**Comment by jamtur01** [comment] 2017-06-25 19:38
Using Tab also fixes it for me.

**Comment by klinker24** [comment] 2017-07-03 17:37
This should be fixed now, with 1.8.6 of the chrome extension. It will be available shortly: https://github.com/klinker41/messenger-chrome/commit/207e391d064c326b92693bc111072bb19549292b

**Closed by klinker24** 2017-07-03 17:37 UTC
Labels: Bug, Chrome, Not Enough Information
