### ISSUE TITLE
Cannot delete conversation through Chrome extension

### ISSUE THREAD

**Issue by ahatzz11** [klinker-apps/messenger-issues#153] opened 2016-11-17 16:57 UTC
### Cannot delete conversation through Chrome extension

**Device with issue:** Macbook Pro running OSX 10.11.6 and Chrome v55
**Primary device:** Google Pixel XL running Android 7.1
**App version:** 1.9.0.681
**Steps to reproduce:**

1. Click the chrome extension
2. Go to a convesation
3. Click on the 3 dot menu
4. Select "Delete conversation"

A chrome popup to confirm the delete will pop up and immediately disappear, making it impossible to delete via the chrome extension.

**Additional information:**

**Possible solution:**

Add a confirmation from within the extension instead of using the chrome popup?

**Comment by klinker41** [comment] 2016-11-17 17:14
Please be sure to search before posting a new issue, duplicate of https://github.com/klinker-apps/messenger-issues/issues/19

**Closed by klinker41** 2016-11-17 17:14 UTC

**Comment by ahatzz11** [comment] 2016-11-17 17:16
I did a quick look and couldn't find anything. Thanks @klinker41!
