### ISSUE TITLE
macOs Desktop App: Messages sent via desktop app appear in wrong order while viewing on phone

### ISSUE THREAD

**Issue by vinayverghese** [klinker-apps/messenger-issues#930] opened 2019-10-16 19:12 UTC
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** MacBook Pro on MacOS 10.15
**Primary device:** Samsung S10 (SM-G973U1) on Android 9
**App version:** Ex: v4.12.0.2614

**Describe the bug:**
Whenever messages are sent via desktop app, the message sent appears before older messages (reverse chronological order)

**Expected behavior:**
Messages sent via desktop app appear in same order as sent, and would appear the same as on device as desktop.

In screenshots, the most recently sent reply to sender appears on top. So the desktop and device look the same, but order changes on both.

**Screenshots:**
Desktop and device screenshots attached.

![device](https://user-images.githubusercontent.com/10580258/66950866-3a0f9000-f027-11e9-9141-963b9a556e03.jpg)
<img width="717" alt="desktop" src="https://user-images.githubusercontent.com/10580258/66950867-3a0f9000-f027-11e9-955c-d30ca3783493.png">

**Comment by klinker24** [comment] 2019-10-16 19:14
Duplicate of #791.

The timestamp on your computer is not the same as the timestamp on your phone.

**Closed by klinker24** 2019-10-16 19:14 UTC
