### ISSUE TITLE
Windows 10 app

### ISSUE THREAD

**Issue by dabookbinder** [klinker-apps/messenger-issues#411] opened 2017-08-15 21:51 UTC
I looked and I couldn't find any mention on your site, google, or here. Is there a windows 10 app in development? If not, could there be? :) I would totally use the chrome app but google notifications are insufferably bad. Plus I just always like using native apps. But with the google notifications the problem is there is no timeout and they hover for awhile which is frustrating when I'm working on something time sensitive. mysms has one but I far prefer your messaging platform. Anyway, just a suggestion. Thanks!

**Comment by klinker24** [comment] 2017-08-15 22:02
It is in the works, yes. 

Here is the page it will be when it is live: https://messenger.klinkerapps.com/overview/platform-windows.html
Here is the issue you can watch to track progress: https://github.com/klinker-apps/messenger-issues/issues/296
And here is an update from a few weeks ago, talking about the preparation for it: https://blog.klinkerapps.com/pulse-real-time-web/

I am going to close this one out as a duplicate of the other that I linked. This should be coming soonish, but I have a few other things I want to finish before making this one

**Closed by klinker24** 2017-08-15 22:02 UTC
