### ISSUE TITLE
Web Auto Update

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [klinker-apps/messenger-issues#150] opened 2016-11-16 17:55 UTC
**Request:**

The website would auto update whenever a new message is received and display a notification (in supported browsers). Also, possibly change the title of the tab (like Slack does) to have an unread indicator.

**Implementation Notes:**

Probably could be implemented using [HTML5 Server-Sent events](http://www.w3schools.com/html/html5_serversentevents.asp). Less overhead/work than Web Sockets and [suits the use case better](http://stackoverflow.com/questions/5195452/websockets-vs-server-sent-events-eventsource).

**Comment by klinker41** [comment] 2016-11-16 18:22
Duplicate of https://github.com/klinker-apps/messenger-issues/issues/76?

**Comment by jeffreyssmith2nd** [comment] 2016-11-16 18:31
Yeah that looks like it covers it. Somehow I missed that in my search. It may be worth considering the Server-Sent events I mentioned to prevent locking people into Chrome, but you can close this issue. Sorry for the dupe.

**Comment by klinker41** [comment] 2016-11-16 18:33
No problem, thanks for the suggestion!

**Closed** 2016-11-16 18:32 UTC
