### ISSUE TITLE
Entered text erased when message received

### ISSUE THREAD

**Issue by bobmac727** [klinker-apps/messenger-issues#814] opened 2019-01-01 18:33 UTC
**Device with issue:** Samsung S9, SM-G960U, Android OS 8.0 Oreo
**Primary device:** Samsung S9, SM-G960U
**App version:** v4.34.2313

**Describe the bug:**
Like the app.  While typing a message to a group, lost part of what I was typing when a new text came in from one of the group members and a notification was displayed.  Happened 3x while typing a message to that group.  Don't know if it does the same thing if a text comes in from another source.

**Expected behavior:**
Don't lose what I was typing when I go back to the message I was typing

Have been a beta tester in the past for work related software and would be happy to help out if needed.

Thanks,

Bob

**Comment by klinker24** [comment] 2019-01-01 18:53
Can you give me steps to reproduce it? Does it happen consistently? I am not seeing this on my phone.

**Comment by bobmac727** [comment] 2019-01-01 19:40
Thanks for getting back to me so quickly.
-I was in the app this afternoon texting some friends in  a group text.
-I was typing when a notification came in, pressed the notification banner, read the text,  went back to typing and part of the message was still there.
-ie. a sentence  up to the period (.) and the few words i typed after we're gone,
started retyping another text came in from the same group, pressed the notification banner read it went back and message up to the period was still there, what i had typed after was gone.
- same scenario happened a third time.  pressed the notification banner.  kinda annoying but the beta tester in me wanted to figure out what was going on :)
-When i was typing, the part after the period was wiped out.  almost like the pressing the notification banner cleared the cache out part of the message.  (don't know if this is the way it works, i'm a user not a programmer.)
-This happened three times when i was typing, maybe that has something to do with it?.  havent been texting since so i'll keep an eye on it going forward and see if it happens again.  This is what happened to me.  I like the app and will continue to use it.

Bob

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by klinker24** [comment] 2019-01-02 02:35
To summarize that, you are exiting the current conversation and just going to a different conversation by clicking the new notification. When you do that, it loses the draft.

Sorry, that was a bit difficult for me to follow and understand.

**Comment by bobmac727** [comment] 2019-01-06 22:00
sorry, i was describing what was happening.

typing in group or single person conversation(this happened a different time), a notification came in everything i was typing is gone, went away, erased.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rovindrasingh** [comment] 2019-01-07 22:12
This is what I'm experiencing with my Pixel 3 XL, hope this clears it up a bit. When in a group chat, if I have a message typed up and it was saved as a draft (by leaving the app and returning) once I return to the app and for example decided to clear that message and type something new or add to the message that was drafted the original draft will return and overwrite everything whenever someone in the chat sends a new message.

**Comment by klinker24** [comment] 2019-01-16 22:00
This commit fixes it.

https://github.com/klinker41/messenger/commit/c69abe1b37df3aaebc71dfee240aa81bf1e68875

This will not be released with 2.5.0 that is being released tomorrow. It will come with whatever version is next.

**Closed by klinker24** 2019-01-16 22:00 UTC
Labels: Not Enough Information

**Comment by GraphiteWingedBird** [comment] 2021-04-09 15:59
I don't think this is fixed as it happens to me fairly regularly. However I don't believe notifications are the issue because the group chat I use I don't receive notifications. It does seem to happen in both group chats and one to one chats.
