### ISSUE TITLE
Time sent by recipient

### ISSUE THREAD

**Issue by armaninyow** [klinker-apps/messenger-issues#826] opened 2019-01-31 02:49 UTC
Hi, dev! I know I already posted this on G+ but I just want to know what you feel about this.

I'm suggesting for an option to replace the timestamp of the incoming messages received by my phone with time sent by the recipient.

What do you think?

**Comment by klinker24** [comment] 2019-01-31 02:52
Duplicate of #146.

**Closed by klinker24** 2019-01-31 02:52 UTC
