### ISSUE TITLE
Web to phone not syncing resulting in messages not being delivered. 

### ISSUE THREAD

**Issue by btafoya** [klinker-apps/messenger-issues#289] opened 2017-03-20 09:09 UTC
**Device with issue:** Moto X Pure with stock MM rom. 
**App version:** 2.1.2.1057
**Steps to reproduce:**

1. Log into web interface and or chrome extension. 
2. Create or reply to existing messages. 
3. Send
4. Newly created message does not appear on the phone or is sent to the intended recipient. 

**Additional Information:**

It all began after a rom reset after completing a fresh install. Followed your instructions on unlinking the device and reseting and uninstalling several times and have even tested on a clean stock rom with only updates run. 

There is clearly a disassociated message queue preventing the messages from being delivered to the device. Oddly, it syncs to the cloud without issue. 

I purchased the lifetime subscription purely for this feature. Thanks for your time and I hope you can help me resolve this issue.

**Comment by klinker24** [comment] 2017-03-20 12:59
Device -> Cloud is much different than Cloud -> Device. 

When uploading to the cloud, we have a REST API that we write to with simple web requests. When sending from a device, other than your primary phone, the backend delivers messages to your primary phone, to be sent, via data push notifications, through Google's Firebase service.

I would try just deleting your account from the Android app, then recreating it again. This will take anything that is currently on your device, and push it up to the cloud.

**Comment by wizard7926** [comment] 2017-03-20 19:52
I'm having the same issue as well. Will deleting my account from the app and then recreating it remove all conversation customizations, etc?

**Comment by klinker24** [comment] 2017-03-20 20:03
It deletes everything on the cloud, then will push up whatever is on your phone.

**Comment by wizard7926** [comment] 2017-03-21 19:49
How about subscription? How does that work when deleting the account from within the app options?

Would it be easier/better to just wipe the app's data and login again rather than create a new account each time? Or does the account disappear once the account is not linked with the app?

**Comment by btafoya** [comment] 2017-03-21 20:04
@wizard7926 The app remembers your subscription. @klinker24 your advice worked perfectly. Thanks!

**Comment by wizard7926** [comment] 2017-03-21 20:11
@btafoya Thanks! Did you use the app's "Delete Account" option to do that?

**Comment by btafoya** [comment] 2017-03-21 20:36
@wizard7926 Yes, and just recreated the account with the same email. Worked perfectly.

**Comment by btafoya** [comment] 2017-03-21 20:37
Re-opening since @klinker24 marked it as a bug.

**Comment by klinker24** [comment] 2017-03-21 20:42
If it is working, then the bug is going to be marked as resolved for now. I made changes around this the other night, go prevent it in the future.

**Closed by klinker24** 2017-03-21 20:42 UTC
Labels: Android, Bug

**Comment by wizard7926** [comment] 2017-03-21 21:01
@btafoya @klinker24 Deleted account, signed up for a "new" one with same creds, and while message content pushes over to the phone now, they don't act as intended (at least not yet). I can't find any evidence of the phone actually passing along the text information from another source now.

**Comment by klinker24** [comment] 2017-03-21 21:07
Sorry I don't understand what you are talking about... If it makes it to the phone, then the web is doing its job correctly

**Comment by wizard7926** [comment] 2017-03-22 13:06
@klinker24 Apologies, it didn't seem like the texts were actually registering. For example, I would send the message "HELP" to Verizon, which would normally prompt an auto-reply but wasn't. Seems like it works now.

One other thing - my "settings" don't seem to be syncing from the phone. I have rounded message bubbles and it keeps telling me when I refresh from the phone that I don't?

**Comment by klinker24** [comment] 2017-03-22 13:09
You can probably just disable that, and enable it again, on your phone, then refresh.

**Comment by wizard7926** [comment] 2017-03-22 17:08
@klinker24 Yep, it worked to disable and then re-enable. Thanks for your help!
