### ISSUE TITLE
Part of pasted text gets cut off in message entry field

### ISSUE THREAD

**Issue by M-W99** [klinker-apps/messenger-issues#572] opened 2018-01-20 17:53 UTC
**Device with issue:** "Samsung Galaxy S8 running Android 7"
**Primary device:** "Same as above"
**App version:** "2.7.7.1873"
**Steps to reproduce:**

1. Go into a conversation
2. Type "If you get a chance, please go to "
3. Paste "https://ubuntu.com/download/desktop"
4. Observe that "download" gets cut off and only shows "down"

**Additional information:**
![20180120_124128](https://user-images.githubusercontent.com/8368860/35186259-4a396546-fddf-11e7-8510-5e43617f42f5.png)

I was sending a friend a link to download Ubuntu for me since my home Internet connection is horrendous and I noticed that part of the link I pasted got cut off in the message entry field. Once the message is sent, the link shows correctly in the message bubble. This only happens when the link is pasted. If I type it out manually, it shows the whole link. I would imagine that this also happens with similar messages, but I've only verified that it's reproducible with the message I've included here in the steps and screenshot.

**Comment by klinker24** [comment] 2018-01-20 18:00
Seems like an issue with Android's `EditText`, not with Pulse. I am not able to reproduce this issue on my devices
![screenshot_20180120-115932](https://user-images.githubusercontent.com/4874287/35186422-7ea72878-fdd9-11e7-8cd7-da041dd66cde.png)

**Comment by M-W99** [comment] 2018-01-20 18:06
Darn, oh well. I have nothing else to test it on at the moment, but I'll try it on a friend's device soon.

**Comment by AD49613** [comment] 2018-01-23 04:10
Also using SwiftKey, on an LG V20. Problem wasn't reproduced, I get the same result as what dev got. Sorry, hope it helps.

**Comment by M-W99** [comment] 2018-01-23 04:13
Ah, thanks for that. I tried it with the default Samsung keyboard and the same thing happens. Maybe it's an S8 thing. It's not really a big deal though.

**Comment by klinker24** [comment] 2018-01-23 12:10
I am going to close this as not-reproducible then. If you get any other information on it, please feel free to post back and I can re-open it.

**Closed by klinker24** 2018-01-23 12:10 UTC
Labels: Not Enough Information
