### ISSUE TITLE
Conversation not updated when new SMS arrives

### ISSUE THREAD

**Issue by midenok** [klinker-apps/messenger-issues#392] opened 2017-07-24 11:38 UTC
**Device with issue:** ASUS Zenfone 3 Max
**App version:** 2.4.4.1328
**Steps to reproduce:**

1. Mute conversation
2. Open conversation
3. Type some message, don't send
4. Receive SMS

### Result

Conversation is not updated. To refresh conversation close it and open again.

### Expected

New SMS appears in conversation instantly.

**Comment by klinker24** [comment] 2017-07-24 11:59
Can you provide me with a bit more information on this? I have not heard of this before, and can't seem to reproduce anything.

Are you able to reproduce it? Is it only when conversations are muted? 

I am assuming that this is the phone app that you are talking about, or is this on the web?

Any info you can provide will be helpful.

**Comment by midenok** [comment] 2017-07-24 13:09
Phone app. I don't know about whether it is only for muted or not. If I notice what happens for unmuted, I will tell.

**Comment by klinker24** [comment] 2017-07-24 13:24
Ok, are you able to reproduce it then? Sorry I am still struggling to see this issue happen on my end. For muted or unmuted conversations.

**Comment by midenok** [comment] 2017-07-24 13:43
Yes, it reproduced always (several times in a row). And I never saw correct behaviour.

**Comment by klinker24** [comment] 2017-07-24 13:44
Ok, then please try to reproduce it with a non-muted conversation as well, and let me know.

**Comment by klinker24** [comment] 2017-07-31 11:49
Are there any updates on this? I haven't had any other reports of issues around anything like this.

**Comment by midenok** [comment] 2017-08-01 19:13
Yes, it is only for muted conversation. When you unmute conversation, arrived but yet unseen messages immediately show up. Also, newly arrived messages do show up immediately.

**Comment by klinker24** [comment] 2017-08-01 19:21
I am not able to reproduce this at all, unfortunately. 

* I have attempted to send a message to a muted conversation with myself, and the reply came in immediately. 
* I also send myself a message from another phone and the reply came in immediately. 

Looking over the code, muting should have nothing to do with whether or not the conversation gets an update request on a new message. Are you sure that is the only relevant parameter for your case? I think there has to be something else here.

**Comment by midenok** [comment] 2017-08-02 08:42
Yes, installed from Google Play (is it phone version?). Try to get SMS from bank (or whatever have no number, just name).

**Comment by klinker24** [comment] 2017-08-14 13:07
I made a refactoring change for this, here: https://github.com/klinker41/messenger/commit/d85422406f4c596e87b9e4d3b45b89c8a7aa78ee

I am going to close this issue, I am thinking it should be fixed, but I still don't think that it really had anything to do with being muted. Once the update comes out, it would be nice if you could follow up and let me know if this is fixed.

**Closed by klinker24** 2017-08-14 13:07 UTC
Labels: Android, Bug, Not Enough Information
