### ISSUE TITLE
Adding Select, Mark Unread, Delete Features to Desktop App

### ISSUE THREAD

**Issue by ayen1** [klinker-apps/messenger-issues#733] opened 2018-08-21 14:29 UTC
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Windows 10
**Primary device:** Pixel
**App version:** 4.0.2 on Pixel, 3.0.1 on Windows
**Steps to reproduce:**

1. Pin Pulse to taskbar (icon is just the logo)
2. Receive incoming message on desktop
3. Notice that Pulse icon now has red circle over it
4. Click on desktop notification, opening Pulse, reading message
5. Notice that the Pulse icon _still_ has red circle over it

**Additional information:**

When I get a new message, the icon looks like so.
![image](https://user-images.githubusercontent.com/31419491/44407627-9f074d00-a52c-11e8-88eb-30c591e487b7.png)
It doesn't go back to the icon below as I would expect after reading the unread message.
![image](https://user-images.githubusercontent.com/31419491/44407732-d544cc80-a52c-11e8-80d9-c0b21c66855d.png)

Love this app, keep up the great work!

**Comment by klinker24** [comment] 2018-08-21 18:45
So how do you get it to return to the "read" state? It should be cleared when you have no unread conversations. If you think that you don't have any unread conversations and can confirm that on the phone app, just use the "refresh account" option on the phone app.

**Comment by ayen1** [comment] 2018-08-21 19:02
I found the issue. I had a very old message that was unread that was causing it to not change.

Let me know if I should create a new issue, but a feature request that I might suggest for the desktop app is to mirror those on the mobile app, like selecting conversations, see only unread messages, mark messages as read, and delete messages. These features are available in the mobile app, but I have not been able to find them in the desktop app.

**Comment by klinker24** [comment] 2018-08-21 19:06
Duplicate of #718

**Closed by klinker24** 2018-08-21 19:06 UTC
