### ISSUE TITLE
Text messages missing

### ISSUE THREAD

**Issue by mbeland2** [klinker-apps/messenger-issues#512] opened 2017-11-21 14:03 UTC
**Device with issue:** Samsung Galaxy S7 SM-G930W8
**Primary device:** Samsung Galaxy S7 SM-G930W8
**App version:** 2.6.3.1743
**Steps to reproduce:**

General Description:  Noticed, as of late, that I am not getting certain text messages.  Yesterday, my wife specifically asked me why I hadn't replied to her message.  After further investigation, and testing, I was able to reproduce the issue.  In short, messages are being received by the device, in the default messaging app, but not by the Pulse app.  This is intermittent.  Testing was done while Pulse was set as the default messaging app.

For reference,  Phone 1 is originating device messages are being sent from, which does not have Pulse installed, and is using the default messaging app.  Phone 2 is the device with Pulse app installed, as the default app.  

1. Send messages from Phone 1, individually, as 1,2,3,4...  in sequence, to see what messages are being missed by Phone 2
2. Checked Pulse app on phone 2, and received only some of the messages, but was able to reply sequential messages, in the same manner, with no messages missed, to Phone 1.
3. Opened default messaging app on Phone 2, and all messages are appearing.

These steps were repeated several times with both phones rebooted and turn off for a period of time, and results were always consistent, Phone 2 did not always get all the messages received.

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

Nothing more specific to provide, other than to mention that I have since moved back to default messaging app, until issue is resolved.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine. You can delete this section.

No idea as to root cause and possible resolution, sorry...

**Comment by klinker24** [comment] 2017-11-21 14:30
Not really sure what to say about this. 

I don't have control over the sending and receiving process. All messages get received through the phone, by your system. Android controls the reception process, since there is such tight carrier integration. When Android gets a new message, it then notifies any SMS apps on your phone through a `BroadcastReceiver`.

Similarly, when you are sending a message, Pulse will hand off that message to your system, to make the carrier integration and send the message. Then Android will update the sent/delivered status of the message, when it hears back from your carrier.

Pulse doesn't control most of this process. The app is forced to rely on your device/system, as all third party apps do.

**Comment by RyVee** [comment] 2017-11-22 01:32
I'm not sure how related this is but I am seeing messages appear in the main feed preview but when I open up the specific contact conversation the message isn't there at all. I'm using an AT&T LG G6 updated to the latest software.

**Comment by krwilson8** [comment] 2017-11-24 03:44
Luke, your response indicates that you did not read, or did not understand this ticket. He specifically noted that the phone does receive the missing messages and they are viewable in the messages app that comes with android. The messages only don't show up in your app so there is a disconnect between android and pulse. I have the same problem and it makes Pulse unusable, which is unfortunate because the device syncing feature is a great idea.

**Comment by klinker24** [comment] 2017-11-24 11:37
I read and understood the ticket. My response stands as is. 

Since this is a developer site, I have no problem pointing you to the resources on how SMS messages are received:

https://android-developers.googleblog.com/2013/10/getting-your-sms-apps-ready-for-kitkat.html?m=1
https://stackoverflow.com/questions/11435354/receiving-sms-on-android-app
https://githuub.com/klinker41/android-smsmms

Please tell me what I am missing and how I should be doing it, if you think that this is incorrect.

**Comment by krwilson8** [comment] 2017-11-24 12:54
I never said that you were subscribing to the broadcast incorrectly. But there is certainly something wrong if your app has missing messages that other apps (ones that aren't even the default sms provider), are displaying properly.

Your refusal to recognize this issue as valid is absolutely terrible customer service and I sincerely regret spending money to support a independent developer such as yourself.

**Comment by klinker24** [comment] 2017-11-24 13:05
Please see the first link I posted. Apps that are not the default receive a different broadcast than the default app, so that is irrelevant.

Feel free to suggest how you would do this, then you can be part of the solution. This is a developer forum for collaboration. I haven't closed the issue, so clearly I am not discounting it.

I encourage you to understand the process and work for a solution rather than just complaining. Otherwise, GitHub probably isn't the best avenue for your feedback

**Comment by krwilson8** [comment] 2017-11-24 13:26
Luke, since your app isn't open source and none of us here can look at your source code to suggest a fix, determining a solution is on you. Also, you're the one making money from the app, we are not here to investigate problems for you. If you truly believe it's a problem with the broadcast receiver I invite you to work with Google and other developers of SMS apps to come up with a solution.

Also, my point is about other apps working fine is entirely relevant even if you want to pretend otherwise. Whenever I have Textra as my default SMS app all messages are displayed and I haven't noticed missing messages. Missing messages are easily noticed in group messages and I've only experienced the problem with Pulse so I believe it's an isolated issue related to something Pulse is doing. It's a shame because the app is great otherwise and I really want to love pulse and use it full time, but I run into this issue every time I try pulse. And it's spanned multiple phones. Maybe you could collaborate with the developers of Textra and learn how they do it since you don't seem to want to investigate the intermittent problem yourself.

**Comment by krwilson8** [comment] 2017-11-24 13:57
I'm not really sure why you think we are your collaborators. We're your customers and because this the avenue you have chosen for bug reporting this is what we can use. Just because it's github, that doesn't automagically obligate us to help you fix your code. Most of your customers aren't developers.

I've paid you ten dollars. Cut us in on your profits and give us access to your private git hub repo so we can view code and push fixes. Then you'll have collaboration. Until then, fix your own bugs and stop telling customers they are wrong.

**Comment by klinker24** [comment] 2017-11-24 14:14
The vast majority of Pulse users use it for free. I have a number of other methods that you can provide feedback if you aren't interested in the follow-up and contributing to the solution. All of these options are for non-developers.

* Google+
* Email
* Twitter 
* Hangouts
* Or really any way that you want to get ahold of me. I have had users reach out on LinkedIn, Facebook, and just about any social media platform that is available. Clearly I am very responsive and receptive to your issues.

I am not seeing any place where I have told anyone that are wrong. I have presented the facts and provided you with references for how the application and the process works. You have implied by yourself that your assumptions were incorrect, now you are getting upset at me about it.

Please see this repo for the relevant code in Pulse and where you can suggest the fix on the open source project. Just because Pulse is not open source, doesn't mean that pieces of it are not. The SMS related code can be seen here:

https://github.com/klinker41/android-smsmms

**Comment by krwilson8** [comment] 2017-11-24 14:32
I've emailed you in the past and you directed me here. This exact issue was reported on Google+ on November 16th with no response from you. Someone even comments that this has been an ongoing problem and knows all about your usual response of Android handling the messaging and that it's not your problem.

I suggest you remedy this before you alienate more users of your otherwise great app.

**Comment by klinker24** [comment] 2017-11-24 14:55
If you have any suggestions on why this is happening and how to solve it, based on the open source project I have directed you to, feel free to comment back here. 

I have laid out how the process works and provided sources to validate that process. So at this point, that will continue to be my response. When you are forced to rely on outside processes, there is inevitably a chance of failure. Thank you for the feedback.

**Comment by krwilson8** [comment] 2017-11-24 15:02
In other words you don't know the problem, or how to fix it, and won't try. Got it.

**Comment by klinker24** [comment] 2017-11-24 15:15
Correct, I don't know the problem or how to fix it, that is very obvious and why I have a GitHub issue tracker for help.

"Won't try" though, I am here responding to you. So that rules that out. 

Enjoy your day, please don't post again if you are not contributing to the solution or providing more information on the problem, which you have not done so far. Otherwise I will block you from posting here and ruining future discussion from others that would like to help solve the problem.

**Comment by krwilson8** [comment] 2017-11-24 15:30
Here's a constructive suggestion then. Log messages received and attempt to reproduce the problem. The original poster listed the steps he used to reproduce it, as well as the device used. I can tell you that same issue occurs on both pixel 1 and pixel 2.

Log messages received by the broadcast receiver in your library that you keep linking. That will help you determine if it is indeed the broadcast receiver not sending you messages. Log when messages exit your library. Log when they are received by Pulse. And log when they are displayed by pulse.

That should let you determine where the disconnect is. Either your library never receives them, drops them due to an exception, they get lost in the sending of them to Pulse, or pulse won't display due to an error.

You can't expect anyone to build a test app using your library to debug this for you. If you narrow down the location of the problem then you can begin to ask for help in solving it.

**Comment by klinker24** [comment] 2017-11-24 15:36
Pulse's receiver does log any exceptions that would result in a message not being saved after making it to the receiver. Feel free to post a log of reproducing the issue.

**Comment by klinker24** [comment] 2017-11-25 13:44
This commit changes the receiver to just start a background service to handle the new message: https://github.com/klinker41/messenger/commit/4c418267317b102d7a31b67f19bb343728251bd0

I don't think that will have any effect, but maybe.

**Comment by HearMeWhisper** [comment] 2017-11-25 17:43
I too am having an issue, where I have not had any issues with any other such third party sms app. Is there anyway perhaps a logcat would help at all?  Anything I can do to help

**Comment by krwilson8** [comment] 2017-12-07 14:12
It's more prevalent with mms if that helps. I'm usually tipped off by someone commenting in a group and it seems out of context. When I check the default messages app, or textra, the pictures are there.

**Comment by klinker24** [comment] 2017-12-07 14:23
We track MMS issues in #101. This is *very* different from missing SMS.

**Comment by krwilson8** [comment] 2017-12-07 14:27
Luke, are you saying my comment isn't related? I believe it is exactly the same thing as what the op described. The MMS images appear in the default app and are indeed received by the device but are not shown in pulse. They are shown in the default messaging app and in Textra.

**Comment by klinker24** [comment] 2017-12-07 14:32
Yes, that is what I am saying. This issue is discussing text messages, SMS. For MMS issues, you can comment on #101. This issue doesn't have anything to do with images or MMS and your comment was the first time it was mentioned. The original issue specifically says text messages.

**Comment by krwilson8** [comment] 2017-12-07 14:39
Why the hostility? I'm simply giving you another data point and saying I've seen the same thing with MMS and it seems to be more prevalent for MMS than SMS, at least for me.

**Comment by klinker24** [comment] 2017-12-07 14:42
No hostility from me, I am simply redirecting you somewhere else if you issue isn't related to this one. It is pretty clear from the thread I am redirecting you to that MMS doesn't work perfectly for everyone.

**Comment by krwilson8** [comment] 2017-12-07 14:47
Fair enough. I still think the two issues are related.

**Comment by klinker24** [comment] 2017-12-07 14:51
If you check out the open source project I have linked you to, you will see how vastly different sending and receiving SMS and MMS are. There is basically no similarity between the two protocols and how they work with Android.

**Comment by krwilson8** [comment] 2017-12-07 17:22
Here's another data point. If you perform a resync messages inside pulse the missing messages appear.

**Comment by klinker24** [comment] 2017-12-07 18:06
I will add a reconciliation check with the internal database, in the receiver. If the receiver isn't getting run though, this won't do any good.

**Comment by rattrick1** [comment] 2017-12-13 16:02
@krwilson8 Have you tried to install another messenger app to run alongside Pulse to see if the messages are getting received in there? I have the stock Google Messages and when I receive a duplicate message in Pulse, Google Messages shows it correctly.

**Comment by krwilson8** [comment] 2017-12-13 16:06
I'm not having any issues with duplicate messages. I'm occasionally missing messages in pulse that I see in other messaging apps.

**Comment by rattrick1** [comment] 2017-12-13 16:08
I have seen that previously and my wife had to uninstall because of this issue. Can't say I've seen that in awhile, where I'm just flat out missing them. I get duplicates in Group Messages and when that happens Pulse doesn't get the message but other apps do.

**Comment by UnkeptFir** [comment] 2018-01-03 19:33
I was having a similar issue within the app, where messages would not always be replicated into Pulse. After some digging and settings-tweaking, I was able to get around it and have not missed any messages (as far as I can tell).

1. Uninstall any other SMS/MMS apps you might have installed other than the default SMS/MMS that came with your phone (e.g. I unistalled Textra, which I was using to see if the messages were received there, like @rattrick1 suggested).
2. Go to your phone's Settings -> Apps -> Default SMS/MMS app (Messages, Android Messages, or other) -> Storage -> "Clear Data" . This will put your default app to it's "default" state before you've ever opened the app. DO NOT OPEN THE DEFAULT SMS/MMS AFTER THIS STEP.
3. Go to your battery optimizer
Through Pulse: Sidebar -> Help & Feedback -> Disable Battery Optimization -> Show all apps. Then, find both Pulse and your default SMS/MMS and **disable battery optimization for both apps.**
4. Retry your tests. I haven't checked to see if you can re-enable Battery Optimization for Pulse and keep it disabled for SMS/MMS and have this work, but Pulse is such a low battery drag on me that I keep both optimizations disabled for peace-of-mind. 

_To my knowledge, I haven't missed any messages (and haven't observed any out of context texts, since following the above steps._

**Comment by rattrick1** [comment] 2018-01-03 19:48
Thanks @UnkeptFir, I have tried this and will see how it works. Appreciate the feedback.

**Comment by krwilson8** [comment] 2018-01-20 00:29
This may be unrelated but I have a feeling it's the same problem. I have another data point that leads me to believe it's a display issue or something similar inside pulse. 

I've just seen an issue where on my secondary device I could see the last text I sent to my wife within the conversation list preview, but when I clicked on the conversation the last message from her and my last message to her (that I sent on my primary device) were missing. So the app definitely received the messages. In this case it was through the database cloud sync instead of through androids broadcast, but I think it's relates to this issue because it clearly received the message but wasn't able to display it inside an actual conversation for some reason.

**Comment by klinker24** [comment] 2018-01-20 01:08
I don't think that has anything to do with this issue. This issue is around receiving messages, that issue is around pushing that message out across devices. They aren't similar or related. I haven't heard from anyone having this issue for over a month.

**Comment by klinker24** [comment] 2018-02-03 19:20
I am going to close this issue. I haven't had any reports of missing SMS for over a month. 

* If you are interested in MMS issues, please see #101. 
* If you have feedback regarding this issue or you feel as though it is still an issue, please provide me with any reproducible steps that I will be able to use to solve the problem

**Closed by klinker24** 2018-02-03 19:20 UTC
Labels: Android, Not Enough Information

**Comment by fleapower** [comment] 2018-06-04 13:11
krwilson8, did you ever figure out a solution to this or did you stop using Pulse?  I'm having the _exact_ same issue.  Luke pointed me to the MMS help on his site without any improvement.  Thanks.

**Comment by xaviervilla** [comment] 2018-06-06 18:48
I started the Pulse free trial for 7 days, and already 3 hours into using the app I have had this exact issue. Facebook Messanger, Signal, and the default Android messaging app all receive and display the messages that Pulse refuses to acknowledge. (Android N on Samsung S7 Edge)

**Comment by xaviervilla** [comment] 2018-06-06 19:27
This issue should certainly not be closed. Thanks for your attempt @UnkeptFir , however the issue persisted after following your workaround exactly. Pulse has already ignored 5 SMS messages since I started using it 3 and a half hours ago at about a 30-40% ignore/acknowledge ratio. It's unfortunate because I think it's an awesome app otherwise, but fortunately there are alternatives.

**Comment by klinker24** [comment] 2018-06-06 20:04
@xaviervilla I have not heard from anyone on this issue for 6+ months. You should ensure that the app is set as your default messaging app. This issue specifically is for SMS, not MMS messages. For tips around MMS, please see #101. With that kind of timetable and the number of users that are active on the app every day, I can pretty confidently that this has been solved.

Your statistic is way above what this thread was discussing, so your problem definitely isn't the same. These were missing half a percent of messages, not 30-40%.

**Comment by o0beaner** [comment] 2020-08-20 22:50
I would like to reopen this, as I am experiencing this issue, specifically related to SMS messages.

This way in which this issue manifests is as follows:

* I do not receive SMS messages from one particular contact
* This contact does receive SMS messages from me
* I do receive MMS messages from that contact
* In those MMS messages, the friendly name for that contact is displayed properly
* If I attempt to create a new conversation with that contact, they are not present in Pulse's contact list

The above conditions are 100% static and reproducible for me.

I'm not sure what I can do to troubleshoot, or provide in order to help figure this out.
