### ISSUE TITLE
Notifications marked read without seeing them

### ISSUE THREAD

**Issue by ohmybrew** [klinker-apps/messenger-issues#516] opened 2017-11-23 15:25 UTC
**Device with issue:** Macbook Pro High Serra (Chrome + Desktop app), Android 7.1.2 on Moto G5
**Primary device:** Moto G5
**App version:** (newest)?
**Steps to reproduce:**

1. Open Chrome for Pulse, or the desktop app
2. Have it in the background, with a contact conversation going, not active/focused
3. Have that contact message you
4. Notification flashes on the phone for a quick second and goes away (it says its read)
4 a. The desktop app shows the notification in the top right of the Macbook screen, also marks it as read even though I haven't seen it.

I'm sorry if this is default behaviour, I just think it shouldn't be marked read unless the window is active/focused? If its default, then no worries :) wasn't sure if it was a bug or not (which could be subjective).

If the Chrome tab is closed, or the desktop app is closed, the notification on the phone stays active (not marked read) until I open it.

**Comment by ohmybrew** [comment] 2017-11-23 17:21
Minimized, I don't think so. I will grab a contact and confirm this for you. I'll try to grab a video as well for you of it.

**Comment by klinker24** [comment] 2017-11-23 17:30
You can text yourself. I am not going to look at this today though, it's Thanksgiving, so you don't need to worry about it right now.

**Comment by ohmybrew** [comment] 2017-11-23 17:31
Oh for sure man! Just wanted to note it. I will test and confirm for you, you relax and enjoy the holiday.

**Comment by jcady** [comment] 2017-11-24 00:00
I'll also add that this is now happening to me. This just started happening in the last day or two. Using the Mac desktop app with a conversation with person X open. If person X texts me (even if window isn't focused or computer is closed), I will get the notification sound on my phone and then it is immediately marked as read.

Happy Thanksgiving!

**Comment by klinker24** [comment] 2017-11-25 14:11
I have not been able to replicate this issue, but I have changed the way that the focus/visibility gets tracked on the web, with this commit: https://github.com/klinker41/messenger-web/commit/1fea4f94d4c9f57d12d9e2787c0f0e393f65e2ee

This should fix the issue on the desktop apps, I think. It will roll out to everyone over the next few days. Let me know if you guys are seeing any behavior changes around this issue.

**Comment by BlakeBiggs** [comment] 2017-11-25 18:59
I've been having the same issue with the Chrome client. Not minimized, but the window is not in focus.

**Comment by joshkendrick** [comment] 2017-11-28 15:54
I'm seeing this as well. I found this github issue while looking to see if it was reported/anyone else was also having it.

I have the latest Android update, and I'm using the Chrome app, looks like v1.7.8 last updated 11/17. I'm betting your fix isn't in the Chrome app yet since your fix was committed on 11/25..?

Thanks! Great app! 😍

**Comment by klinker24** [comment] 2017-11-29 12:43
Pulse uses the page visibility API in javascript to know whether or not the page is active on the screen. If any portion of the web page, Chrome app, or desktop app is visible (even when not in focus), the visibility API will pick up that the app is active, load the new message, and dismiss the notification.

This visibility API is the only way I know how to manage it. So this would be working as expected, in my opinion. If you know of any other way to get this status, feel free to share and I can re-open this issue

**Closed by klinker24** 2017-11-29 12:43 UTC
Labels: Bug, Native Desktop

**Comment by joshkendrick** [comment] 2017-11-29 13:53
Hm it didnt used to work this way though... I've been using Pulse for about a year and this issue has only cropped up in the last, month maybe?

Also I'm seeing this if the Chrome app is completely hidden from view, completely obscured by another window. The reason this is an issue is because frequently since this has started happening, I've missed entire sets of text messages. Based on your description of how the app works the Chrome app gets the message, thinks I saw it, and dismisses the notification, but you also don't get notified on your phone either.

**Comment by klinker24** [comment] 2017-11-29 13:56
The functionality has recently changed.

Previously, if you had a conversation open on the web and new messages came in, it would never mark that conversation as read or dismiss the notification until you replied or you switched to a different conversation and came back.

Now, the message notification get dismissed on the phone and the conversation marked as read if the app is visible on the desktop.

To me, this is the expected functionality. It will not dismiss the notifications if the window is minimized.

**Comment by joshkendrick** [comment] 2017-11-29 14:56
Ah, ok that makes sense.

I think the issue is somewhere "app is visible on the desktop" is either broken, or my definition is wrong :) To me, if the (in my case Chome app) is open, but entirely behind a few other applications, it's not visible. Maybe the issue is Chrome's javascript visibility API..? I donno.

Thanks for your time @klinker24 !

**Comment by joshkendrick** [comment] 2017-11-29 15:07
Ok, after further testing, the behavior still happens if the chrome app is minimized.

It seems the issue is if I leave a conversation open on the Chrome app. If I click "conversations" to go back to the list of conversations, the notification stays on my phone and I get the chrome notification.

This may still be expected application behavior, but for anyone else running into this, you'll need to start closing conversations in order to get notifications.

**Comment by BlakeBiggs** [comment] 2017-11-29 15:08
The "app is visible on the desktop" is definitely broken. The app can be open, but completely behind other windows (aka not visible) and it will mark new messages as read. 

Even if the visibility was working correctly, what about having the desktop app open and simply just get up and walk away from your computer? You'll never receive a text notification on your phone while you're away. 

Can it be changed to if the user clicks on the thread to mark it as read? I believe this is how the hangouts app works.

**Comment by klinker24** [comment] 2017-11-29 15:47
I will just make it so it doesn't dismiss the notification until you re-enter the conversation, like it used to do.

I am going to continue marking them as read when the conversation is open though.

**Comment by jcady** [comment] 2017-11-29 15:53
Will it still be marked read if the conversation is open, but in the background? For example, I mostly text my SO, so her thread is almost always open. In this case, I could have the window in the background and never see the text notification on my phone.

Maybe an alternative would be waiting to mark it read until one action is taken on the window related to that thread (e.g. thread opened, thread message box newly focused, keystroke made)?

**Comment by ohmybrew** [comment] 2017-11-29 20:16
I deleted both the desktop app and SMS app, reinstalled and re-synced both. I no longer have the issue of it marking messages as read.

Does not matter if the window is in minimized, or in the background (fully/partially), it all seems to work now. Messages are not marked as read until I focus the conversation.

Thanks @klinker24 !
